# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iScoutToolModern.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 880)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #2b2b2b;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 2px solid #555555;\n"
"    border-radius: 8px;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 8px 0 8px;\n"
"    color: #00d4ff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4a90e2;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    min-height: 32px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #357abd;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2968a3;\n"
"}\n"
"\n"
"QPushButton#btnIScoutGoHome {\n"
"    background-color: #28a745;\n"
"}\n"
"\n"
"QPushButton#btnIScoutGoEnemy {\n"
"    background-color: #dc3545;\n"
"}\n"
"\n"
"QPushButton#btnIScoutClearAll {\n"
"    background-color: #6c757d;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: #404040;\n"
"    alternate-background-color: #4a4a4a;\n"
"    gridline-color: #555555;\n"
"    border: 1px solid #666666;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #4a90e2;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #353535;\n"
"    color: #00d4ff;\n"
"    padding: 8px;\n"
"    border: 1px solid #555555;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #404040;\n"
"    border: 2px solid #555555;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    font-size: 12px;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4a90e2;\n"
"}\n"
"\n"
"QLabel#lblTimer {\n"
"    background-color: #1a1a1a;\n"
"    border: 3px solid #00d4ff;\n"
"    border-radius: 12px;\n"
"    color: #00d4ff;\n"
"    font-family: \'Consolas\', \'Monaco\', monospace;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    background-color: #404040;\n"
"    border: 2px solid #555555;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    font-family: \'Consolas\', \'Monaco\', monospace;\n"
"    color: white;\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"    border-color: #4a90e2;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #353535;\n"
"    color: #ffffff;\n"
"    border-top: 1px solid #555555;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #353535;\n"
"    color: #ffffff;\n"
"    border-bottom: 1px solid #555555;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #4a90e2;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #353535;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555555;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 8px 32px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #4a90e2;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QSplitter::handle {\n"
"    background-color: #555555;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal {\n"
"    width: 3px;\n"
"}\n"
"\n"
"QSplitter::handle:vertical {\n"
"    height: 3px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.controlGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.controlGroup.setGeometry(QtCore.QRect(15, 15, 610, 241))
        self.controlGroup.setMinimumSize(QtCore.QSize(0, 38))
        self.controlGroup.setObjectName("controlGroup")
        self.controlLayout = QtWidgets.QHBoxLayout(self.controlGroup)
        self.controlLayout.setContentsMargins(-1, 3, -1, 3)
        self.controlLayout.setSpacing(20)
        self.controlLayout.setObjectName("controlLayout")
        self.serverGroup = QtWidgets.QGroupBox(self.controlGroup)
        self.serverGroup.setObjectName("serverGroup")
        self.lblEnemyServer = QtWidgets.QLabel(self.serverGroup)
        self.lblEnemyServer.setGeometry(QtCore.QRect(10, 150, 82, 16))
        self.lblEnemyServer.setStyleSheet("color: #ffffff; font-weight: bold;")
        self.lblEnemyServer.setObjectName("lblEnemyServer")
        self.intHomeServer = QtWidgets.QLineEdit(self.serverGroup)
        self.intHomeServer.setGeometry(QtCore.QRect(100, 20, 71, 32))
        self.intHomeServer.setObjectName("intHomeServer")
        self.lblHomeCoords = QtWidgets.QLabel(self.serverGroup)
        self.lblHomeCoords.setGeometry(QtCore.QRect(11, 67, 56, 16))
        self.lblHomeCoords.setStyleSheet("color: #ffffff; font-weight: bold;")
        self.lblHomeCoords.setObjectName("lblHomeCoords")
        self.intEnemyServer = QtWidgets.QLineEdit(self.serverGroup)
        self.intEnemyServer.setGeometry(QtCore.QRect(100, 140, 71, 31))
        self.intEnemyServer.setObjectName("intEnemyServer")
        self.lblHomeServer = QtWidgets.QLabel(self.serverGroup)
        self.lblHomeServer.setGeometry(QtCore.QRect(11, 31, 77, 16))
        self.lblHomeServer.setStyleSheet("color: #ffffff; font-weight: bold;")
        self.lblHomeServer.setObjectName("lblHomeServer")
        self.intHomeXLoc = QtWidgets.QLineEdit(self.serverGroup)
        self.intHomeXLoc.setGeometry(QtCore.QRect(10, 90, 71, 30))
        self.intHomeXLoc.setMaximumSize(QtCore.QSize(16777215, 30))
        self.intHomeXLoc.setObjectName("intHomeXLoc")
        self.intHomeYLoc = QtWidgets.QLineEdit(self.serverGroup)
        self.intHomeYLoc.setGeometry(QtCore.QRect(100, 90, 71, 30))
        self.intHomeYLoc.setMaximumSize(QtCore.QSize(16777215, 30))
        self.intHomeYLoc.setObjectName("intHomeYLoc")
        self.controlLayout.addWidget(self.serverGroup)
        self.actionGroup = QtWidgets.QGroupBox(self.controlGroup)
        self.actionGroup.setObjectName("actionGroup")
        self.btnIScoutGoEnemy = QtWidgets.QPushButton(self.actionGroup)
        self.btnIScoutGoEnemy.setGeometry(QtCore.QRect(20, 150, 140, 48))
        self.btnIScoutGoEnemy.setObjectName("btnIScoutGoEnemy")
        self.btnViewEnemy = QtWidgets.QPushButton(self.actionGroup)
        self.btnViewEnemy.setGeometry(QtCore.QRect(20, 90, 140, 48))
        self.btnViewEnemy.setObjectName("btnViewEnemy")
        self.btnIScoutGoHome = QtWidgets.QPushButton(self.actionGroup)
        self.btnIScoutGoHome.setGeometry(QtCore.QRect(20, 30, 140, 48))
        self.btnIScoutGoHome.setObjectName("btnIScoutGoHome")
        self.controlLayout.addWidget(self.actionGroup)
        self.statusGroup = QtWidgets.QGroupBox(self.controlGroup)
        self.statusGroup.setObjectName("statusGroup")
        self.lblTimer = QtWidgets.QLabel(self.statusGroup)
        self.lblTimer.setGeometry(QtCore.QRect(11, 31, 161, 60))
        self.lblTimer.setMinimumSize(QtCore.QSize(100, 60))
        self.lblTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimer.setObjectName("lblTimer")
        self.btnResetTimer = QtWidgets.QPushButton(self.statusGroup)
        self.btnResetTimer.setGeometry(QtCore.QRect(10, 100, 161, 48))
        self.btnResetTimer.setObjectName("btnResetTimer")
        self.lblConnectionStatus = QtWidgets.QLabel(self.statusGroup)
        self.lblConnectionStatus.setGeometry(QtCore.QRect(10, 160, 161, 16))
        self.lblConnectionStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblConnectionStatus.setObjectName("lblConnectionStatus")
        self.controlLayout.addWidget(self.statusGroup)
        self.mainSplitter = QtWidgets.QSplitter(self.centralwidget)
        self.mainSplitter.setGeometry(QtCore.QRect(10, 260, 610, 561))
        self.mainSplitter.setOrientation(QtCore.Qt.Vertical)
        self.mainSplitter.setChildrenCollapsible(False)
        self.mainSplitter.setObjectName("mainSplitter")
        self.inputGroup = QtWidgets.QGroupBox(self.mainSplitter)
        self.inputGroup.setMinimumSize(QtCore.QSize(0, 90))
        self.inputGroup.setObjectName("inputGroup")
        self.inputLayout = QtWidgets.QVBoxLayout(self.inputGroup)
        self.inputLayout.setSpacing(4)
        self.inputLayout.setObjectName("inputLayout")
        self.compactInputHeader = QtWidgets.QHBoxLayout()
        self.compactInputHeader.setContentsMargins(-1, -1, 30, -1)
        self.compactInputHeader.setSpacing(15)
        self.compactInputHeader.setObjectName("compactInputHeader")
        self.lblInstructions = QtWidgets.QLabel(self.inputGroup)
        self.lblInstructions.setStyleSheet("color: #cccccc; font-size: 11px;")
        self.lblInstructions.setObjectName("lblInstructions")
        self.compactInputHeader.addWidget(self.lblInstructions)
        self.inputLayout.addLayout(self.compactInputHeader)
        self.txtiScoutBoss = QtWidgets.QPlainTextEdit(self.inputGroup)
        self.txtiScoutBoss.setObjectName("txtiScoutBoss")
        self.inputLayout.addWidget(self.txtiScoutBoss)
        self.targetGroup = QtWidgets.QGroupBox(self.mainSplitter)
        self.targetGroup.setMinimumSize(QtCore.QSize(0, 320))
        self.targetGroup.setObjectName("targetGroup")
        self.targetLayout = QtWidgets.QVBoxLayout(self.targetGroup)
        self.targetLayout.setSpacing(6)
        self.targetLayout.setObjectName("targetLayout")
        self.tableToolbar = QtWidgets.QHBoxLayout()
        self.tableToolbar.setSpacing(8)
        self.tableToolbar.setObjectName("tableToolbar")
        self.btnIScoutLoadTable = QtWidgets.QPushButton(self.targetGroup)
        self.btnIScoutLoadTable.setObjectName("btnIScoutLoadTable")
        self.tableToolbar.addWidget(self.btnIScoutLoadTable)
        self.btnIScoutClearAll = QtWidgets.QPushButton(self.targetGroup)
        self.btnIScoutClearAll.setObjectName("btnIScoutClearAll")
        self.tableToolbar.addWidget(self.btnIScoutClearAll)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tableToolbar.addItem(spacerItem)
        self.lblTargetCount = QtWidgets.QLabel(self.targetGroup)
        self.lblTargetCount.setStyleSheet("color: #00d4ff; font-weight: bold;")
        self.lblTargetCount.setObjectName("lblTargetCount")
        self.tableToolbar.addWidget(self.lblTargetCount)
        self.targetLayout.addLayout(self.tableToolbar)
        self.tblBossList = QtWidgets.QTableWidget(self.targetGroup)
        self.tblBossList.setAlternatingRowColors(True)
        self.tblBossList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblBossList.setRowCount(0)
        self.tblBossList.setColumnCount(5)
        self.tblBossList.setObjectName("tblBossList")
        item = QtWidgets.QTableWidgetItem()
        self.tblBossList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblBossList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblBossList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblBossList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblBossList.setHorizontalHeaderItem(4, item)
        self.tblBossList.horizontalHeader().setStretchLastSection(True)
        self.targetLayout.addWidget(self.tblBossList)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("QStatusBar {\n"
"    background-color: #353535;\n"
"    color: #ffffff;\n"
"    border-top: 1px solid #555555;\n"
"}")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 32))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionSaveConfig = QtWidgets.QAction(MainWindow)
        self.actionSaveConfig.setObjectName("actionSaveConfig")
        self.actionLoadConfig = QtWidgets.QAction(MainWindow)
        self.actionLoadConfig.setObjectName("actionLoadConfig")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionTestConnection = QtWidgets.QAction(MainWindow)
        self.actionTestConnection.setObjectName("actionTestConnection")
        self.actionScreenshot = QtWidgets.QAction(MainWindow)
        self.actionScreenshot.setObjectName("actionScreenshot")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionUserGuide = QtWidgets.QAction(MainWindow)
        self.actionUserGuide.setObjectName("actionUserGuide")
        self.menuFile.addAction(self.actionSaveConfig)
        self.menuFile.addAction(self.actionLoadConfig)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionTestConnection)
        self.menuTools.addAction(self.actionScreenshot)
        self.menuTools.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionUserGuide)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iScoutTool - Evony Automation"))
        self.controlGroup.setTitle(_translate("MainWindow", "Control Panel"))
        self.serverGroup.setTitle(_translate("MainWindow", "🌐 Server Configuration"))
        self.lblEnemyServer.setText(_translate("MainWindow", "Enemy Server:"))
        self.intHomeServer.setInputMask(_translate("MainWindow", "9999"))
        self.intHomeServer.setText(_translate("MainWindow", "0"))
        self.intHomeServer.setPlaceholderText(_translate("MainWindow", "1234"))
        self.lblHomeCoords.setText(_translate("MainWindow", "Home X,Y:"))
        self.intEnemyServer.setInputMask(_translate("MainWindow", "9999"))
        self.intEnemyServer.setText(_translate("MainWindow", "0"))
        self.intEnemyServer.setPlaceholderText(_translate("MainWindow", "5678"))
        self.lblHomeServer.setText(_translate("MainWindow", "Home Server:"))
        self.intHomeXLoc.setInputMask(_translate("MainWindow", "9999"))
        self.intHomeXLoc.setText(_translate("MainWindow", "0"))
        self.intHomeXLoc.setPlaceholderText(_translate("MainWindow", "X"))
        self.intHomeYLoc.setInputMask(_translate("MainWindow", "9999"))
        self.intHomeYLoc.setText(_translate("MainWindow", "0"))
        self.intHomeYLoc.setPlaceholderText(_translate("MainWindow", "Y"))
        self.actionGroup.setTitle(_translate("MainWindow", "⚡ Quick Actions"))
        self.btnIScoutGoEnemy.setText(_translate("MainWindow", "⚔️ Go to Enemy"))
        self.btnViewEnemy.setText(_translate("MainWindow", "👁️ View Enemy"))
        self.btnIScoutGoHome.setText(_translate("MainWindow", "🏠 Go Home"))
        self.statusGroup.setTitle(_translate("MainWindow", "⏱️ Status"))
        self.lblTimer.setText(_translate("MainWindow", "05:00"))
        self.btnResetTimer.setText(_translate("MainWindow", "Reset Timer"))
        self.lblConnectionStatus.setText(_translate("MainWindow", "🔴 Disconnected"))
        self.inputGroup.setTitle(_translate("MainWindow", "📝 Data Input"))
        self.lblInstructions.setText(_translate("MainWindow", "� Paste scout data below (tab-separated format) - Use Ctrl+V to paste"))
        self.txtiScoutBoss.setPlaceholderText(_translate("MainWindow", "Arctic Barbarians Lv5 502M    Free    338    249\n"
"(Boss) Kamaitachi    Lv12    440    267\n"
"\n"
"Paste your scout data here..."))
        self.targetGroup.setTitle(_translate("MainWindow", "🎯 Scout Targets"))
        self.btnIScoutLoadTable.setText(_translate("MainWindow", "📥 Load Targets"))
        self.btnIScoutClearAll.setText(_translate("MainWindow", "🗑️ Clear All"))
        self.lblTargetCount.setText(_translate("MainWindow", "Targets: 0"))
        self.tblBossList.setSortingEnabled(True)
        item = self.tblBossList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "➡️ Action"))
        item = self.tblBossList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "✓"))
        item = self.tblBossList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "🎯 Target"))
        item = self.tblBossList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "X"))
        item = self.tblBossList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Y"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuTools.setTitle(_translate("MainWindow", "&Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.actionSaveConfig.setText(_translate("MainWindow", "&Save Configuration"))
        self.actionSaveConfig.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionLoadConfig.setText(_translate("MainWindow", "&Load Configuration"))
        self.actionLoadConfig.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionTestConnection.setText(_translate("MainWindow", "&Test ADB Connection"))
        self.actionTestConnection.setShortcut(_translate("MainWindow", "F5"))
        self.actionScreenshot.setText(_translate("MainWindow", "Take &Screenshot"))
        self.actionScreenshot.setShortcut(_translate("MainWindow", "F12"))
        self.actionSettings.setText(_translate("MainWindow", "Se&ttings"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+,"))
        self.actionAbout.setText(_translate("MainWindow", "&About iScoutTool"))
        self.actionUserGuide.setText(_translate("MainWindow", "&User Guide"))
        self.actionUserGuide.setShortcut(_translate("MainWindow", "F1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
